#!/bin/bash -eu

if [[ ( ( ! -x /root/bin/tesla_api.py) || ( ! -s /mutable/cache.json ) ) && ( -z "${TESLAFI_API_TOKEN:+x}" ) && ( -z "${TESSIE_API_TOKEN:+x}" ) ]]
then
  exit
fi

# If Sentry Mode was previously disabled, restore it to that state
if [ -e /tmp/disable_sentry_after_archiving ]
then
  log "Restoring Sentry Mode to its previous state (disabled)..."
  /root/bin/tesla_api.py disable_sentry_mode &>> "${LOG_FILE}"
  rm -f /tmp/disable_sentry_after_archiving
fi

if [ -e /tmp/keep_awake_task_pid ]
then
  log "Stopping wake car background task."
  kill "$(cat /tmp/keep_awake_task_pid)" || true
  rm -f /tmp/keep_awake_task_pid

  if [[ ( -n "${TESLAFI_API_TOKEN:+x}" ) ]]
  # TeslaFi Sleep command suspends its polling for the next 15 minutes (by default) to faciliate car's sleep.
  then
    curl -H "Authorization: Bearer $TESLAFI_API_TOKEN" "https://www.teslafi.com/feed.php?command=sleep"
    log "also initiated TeslaFi Sleep Mode to give the car a chance to fall asleep." 
  fi
fi
