name: ShellCheck

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run ShellCheck
        shell: bash
        run: |
          cd "${GITHUB_WORKSPACE}"
          ./check.sh
